### ISSUE TITLE
[Suggestion] 1.18.2 support

### ISSUE THREAD

**Issue by BookWyrm114** [Keksuccino/Spiffy-HUD#14]
it would be really nice to have

**Comment by Keksuccino** [comment]
Spiffy HUD now supports MC 1.18.2! :)

**Comment by BookWyrm114** [comment]
WOOHOOOOOOOOOOOOOOOOOOOOOOOOOOOOO LETS GOOOOOOOOOOOOOOOO

Thank you, so much! I actually tried manually updating it with my limited knowledge of java and it couldn't find and download some minecraft mappings it depended on so I gave up after a few days
