### ISSUE TITLE
1.16.5 running (fancyhud_1.4.2_MC_1.16.2-1.16.5) and Konkrete.....nothing at all.....

### ISSUE THREAD

**Issue by Kilroy5150** [Keksuccino/Spiffy-HUD#2]
Nothing as in nothing. I can't even use the control switch to access the configuration. I am running a lot of mods but no other HUD mods and i don't think any of them should block it. In "Control" the option for the button is there but nothing else.

**Comment by Keksuccino** [comment]
Maybe try to send me your latest.log file (`.minecraft/logs/latest.log`), your mods list  and a more detailed description of your problem, so I’m actually able to help you? :D

**Also try the following:**
- Start your game with only FancyHud and Konkrete and check if it works then
- If it works with FH + Konkrete, try to use only some of your mods and add more over time to see which one is incompatible

**Comment by Kilroy5150** [comment]
Okay, i did a drag and drop of my log but i'm not sure it took it here?

**Comment by Kilroy5150** [comment]
Not sure how good this editor is, i dragged and dropped the log several time but i see notihng.

**Comment by Kilroy5150** [comment]
It's not like i'm new to dragging and dropping, been doing it since the early 90s. It's just that it says it's "uploading latest.log" then vanishes and nothing....Odd.
