### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by Kitieshka** [Keksuccino/Spiffy-HUD#23]
After run decompile, console says that

Execution failed for task ':common:decompile'.
> Failed to calculate the value of task ':common:decompile' property 'javaLauncher'.
   > Failed to calculate the value of property 'languageVersion'.
      > Could not resolve all artifacts for configuration ':common:decompiler'.
         > Could not find org.vineflower:vineflower:1.10.1.
           Required by:
               project :common

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by Keksuccino** [comment]
Don't ask for dev support please. Please use Google to fix Gradle/workspace issues, thank you.
