### ISSUE TITLE
Game hangs for several seconds

### ISSUE THREAD

**Issue by aburone** [Keksuccino/Spiffy-HUD#4]
The game halts for 5-10 seconds every couple of minutes. 
Couldn't identity what was the issue so I ran some profiling...
https://spark.lucko.me/6JpJgcDaw8

**Comment by Keksuccino** [comment]
Lagging seems to be a problem for a small amount of users, but I wasn't able to identify what exactly causes this yet.
It runs fine for me and most other users :o
Your profiling thing only tells me that the game loop is at 100%..CPU I guess? But yeah, sadly that doesn't really helps to identify the crash :(

Will keep trying to fix whatever causes this.

**Comment by Keksuccino** [comment]
This got fixed in v1.4.3! Thank you for your report!
